// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function marginTop(n) {
  return ".mt-" + (String(n) + "");
}

var Spacing = /* module */[/* marginTop */marginTop];

var Utilities = /* module */[/* Spacing */Spacing];

exports.Utilities = Utilities;
/* No side effect */
