// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function toClassNames(strings) {
  return strings;
}

function container(fluid) {
  if (fluid !== 0) {
    return "container-fluid";
  } else {
    return "container";
  }
}

var Layout = /* module */[/* container */container];

exports.toClassNames = toClassNames;
exports.Layout       = Layout;
/* No side effect */
