// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                       = require("bs-jest/src/jest.js");
var Curry                      = require("bs-platform/lib/js/curry.js");
var Bootstrap                  = require("../src/bootstrap.bs.js");
var Bootstrap__InternalHelpers = require("../src/Bootstrap__InternalHelpers.bs.js");

describe("Spacint", (function () {
        return Jest.test("marginTop", (function () {
                      return Jest.Expect[/* toEqual */12]("mt-1", Jest.Expect[/* expect */0](Curry._1(Bootstrap.Utilities[/* Spacing */0][/* marginTop */0], 1)));
                    }));
      }));

var Value = Bootstrap__InternalHelpers.Value;

exports.Value = Value;
/*  Not a pure module */
